[package]
name = "io"
version = "0.1.0"
edition = "2021"


[dependencies]
succinct-zkvm = { path = "../../zkvm" }
succinct-derive = { path = "../../derive" }
serde = { version = "1.0.195", features = ["derive"] }
bincode = "1.3.3"

