[package]
name = "cycle-tracking-script"
version = "0.0.1-test"
edition = "2021"
publish = false

[dependencies]
sp1-sdk = { path = "../../../sdk", version = "0.0.1-test" }

[build-dependencies]
sp1-helper = { path = "../../../helper", version = "0.0.1-test" }
