[package]
name = "zeth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
succinct-zkvm = { path = "../../zkvm" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
zeth-lib = { git = "https://github.com/succinctlabs/zeth-private", branch = "chris/zeth-lib", default-features = false }
