[workspace]
[package]
version = "0.1.0"
name = "tendermint-program"
edition = "2021"

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tendermint-light-client-verifier = { version = "0.35.0", default-features = false, features = [
  "rust-crypto",
] }
serde_cbor = "0.11.2"

# curve25519-dalek = { package = "curve25519-dalek-ng", version = "4.1.1", default-features = false, features = [
#   "u32_backend",
#   "alloc",
# ] }

[patch.crates-io]
# sha2-v0-9-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-v0.9.8" }
# sha2-v0-10-6 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-v0.10.6" }
# ed25519-consensus = { git = "https://github.com/sp1-patches/ed25519-consensus", branch = "patch-v2.1.0" }
ed25519-consensus = { git = "https://github.com/sp1-patches/ed25519-consensus-fork", branch = "patch-v2.1.0" }
# curve25519-dalek-ng = { git = "https://github.com/sp1-patches/curve25519-dalek-ng-fork", patch = "patch-v4.1.1" }
# curve25519-dalek = { package = "curve25519-dalek-ng", git = "https://github.com/sp1-patches/curve25519-dalek-ng-fork", branch = "patch-v4.1.1", default-features = false, features = [
#   "u32_backend",
#   "alloc",
# ] }
# curve25519-dalek = { git = "https://github.com/sp1-patches/curve25519-dalek-fork", patch = "patch-v4.1.2" }
