[package]
name = "patch-testing-script"
version = "0.0.2-test"
edition = "2021"
publish = false

[dependencies]
rand = "0.8"
ed25519-consensus = "2.1.0"
sp1-core = { path = "../../../core", features = [
	"neon",
], version = "0.0.2-test" }
sp1-sdk = { path = "../../../sdk", version = "0.0.2-test" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[build-dependencies]
sp1-helper = { path = "../../../helper", version = "0.0.2-test" }
