[package]
name = "patch-testing-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }

sha2-v0-9-8 = { version = "0.9.8", package = "sha2" }
# Note: Can't have sha2-v0-10-6 and v0-10-8 at the same time due to crate resolution.
sha2-v0-10-6 = { version = "0.10.6", package = "sha2" }
# sha2-v0-10-8 = { version = "0.10.8", package = "sha2" }

ed25519-consensus = "2.1.0"
# We need this because we needed to change the rand version to be compatible with sp1-zkvm's getrandom.
ed25519-dalek-1-0-1 = { git = "https://github.com/sp1-patches/ed25519-dalek.git", branch = "patch-ed25519-v1.0.1", package = "ed25519-dalek", version = "1.0.1"}
ed25519-dalek = { version = "2.1.0", package = "ed25519-dalek" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
curve25519-dalek = { git = "https://github.com/sp1-patches/curve25519-dalek", branch = "patch-curve25519-v4.1.3", package = "curve25519-dalek", version = "4.1.3", default-features = false, features = ["alloc"]}
curve25519-dalek-ng = { git = "https://github.com/sp1-patches/curve25519-dalek-ng", branch = "patch-v4.1.1" ,  default-features = false, features = ["u32_backend", "alloc"]}
alloy-primitives = { version = "0.8", features = ["k256"] }
secp256k1 = { version = "0.29", features = ["recovery", "global-context"] }
rand = { version = "0.8", features = ["std_rng"] }
revm-precompile = { version = "11.0.1", default-features = false, features = ["kzg-rs"] }
