[workspace]
[package]
version = "0.1.0"
name = "tendermint-program"
edition = "2021"

[dependencies]
sha2-v0-9-8 = { version = "0.9.8", package = "sha2" }
sha2-v0-10-6 = { version = "0.10.6", package = "sha2" }
sha2-v0-10-8 = { version = "0.10.8", package = "sha2" }
sp1-zkvm = { path = "../../../zkvm/entrypoint" }

[patch.crates-io]
sha2-v0-9-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-v0.9.8" }
sha2-v0-10-6 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-v0.10.6" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-v0.10.8" }
