[workspace]
[package]
version = "0.1.0"
name = "patch-testing-program"
edition = "2021"

[dependencies]
sha2-v0-9-8 = { version = "0.9.8", package = "sha2" }
# Note: Can't have sha2-v0-10-8 and v0-10-6 at the same time.
sha2-v0-10-6 = { version = "0.10.6", package = "sha2" }
# sha2-v0-10-8 = { version = "0.10.8", package = "sha2" }
ed25519-consensus = "2.1.0"
sp1-zkvm = { path = "../../../zkvm/entrypoint" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
# sha2 = "0.9.8"

[patch.crates-io]
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak-fork", branch = "patch-v2.0.2" }
ed25519-consensus = { git = "https://github.com/sp1-patches/ed25519-consensus-fork", branch = "patch-v2.1.0" }
sha2-v0-9-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes-fork", package = "sha2", branch = "patch-sha2-v0.9.8" }
sha2-v0-10-6 = { git = "https://github.com/sp1-patches/RustCrypto-hashes-fork", package = "sha2", branch = "patch-sha2-v0.10.6" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes-fork", package = "sha2", branch = "patch-sha2-v0.10.8" }
