[book]
authors = ["SP1 Contributors"]
language = "en"
multilingual = false
src = "book"
title = "SP1 Book"
description = "A book on all things SP1"
version = "0.1.0"
mdbook-version = "0.4.0"

[output.html]
theme = "book/theme"
git-repository-url = "https://github.com/succinctlabs/sp1"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[output.html.playground]
runnable = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true

[build]
build-dir = "target/book"

[preprocessor.template]
before = ["links"]

[preprocessor.index]

[preprocessor.links]
