[workspace]
members = ["core"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[workspace.dependencies]
p3-air = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-field = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-commit = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-matrix = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-baby-bear = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-util = { git = "https://github.com/succinctlabs/plonky3.git" }
valida-opcodes = { git = "https://github.com/valida-xyz/valida.git" }
valida-derive = { git = "https://github.com/valida-xyz/valida.git" }

p3-challenger = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-dft = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-fri = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-goldilocks = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-keccak = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-ldt = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-mds = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-merkle-tree = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-poseidon2 = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-symmetric = { git = "https://github.com/succinctlabs/plonky3.git" }
p3-uni-stark = { git = "https://github.com/succinctlabs/plonky3.git" }

curta-core = { path = "core" }
