[workspace]
members = ["core", "cli", "zkvm", "examples/*", "derive"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[workspace.dependencies]
p3-air = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-field = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-commit = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-matrix = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-baby-bear = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-util = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
valida-derive = { git = "https://github.com/valida-xyz/valida.git" }

p3-challenger = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-dft = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-fri = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-goldilocks = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-keccak = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-ldt = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-mds = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-merkle-tree = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-poseidon2 = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-symmetric = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-uni-stark = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }
p3-maybe-rayon = { git = "ssh://git@github.com/succinctlabs/plonky3.git" }

[patch.crates-io]
# Patch sha2 so we can use sha precompiles
sha2 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git", branch = "v0.9.8" }
# Patch time because newer version breaks with older toolchains
time = { git = "https://github.com/time-rs/time.git", rev = "v0.3.28" }