[workspace]
members = ["core", "disassembler", "curta"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3


[workspace.dependencies]
p3-air = { git = "https://github.com/Plonky3/Plonky3" }
p3-field = { git = "https://github.com/Plonky3/Plonky3" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3" }
p3-baby-bear = { git = "https://github.com/Plonky3/Plonky3" }
p3-util = { git = "https://github.com/Plonky3/Plonky3" }
valida-opcodes = { git = "https://github.com/valida-xyz/valida.git" }
valida-derive = { git = "https://github.com/valida-xyz/valida.git" }

p3-challenger = { git = "https://github.com/Plonky3/Plonky3" }
p3-dft = { git = "https://github.com/Plonky3/Plonky3" }
p3-fri = { git = "https://github.com/Plonky3/Plonky3" }
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3" }
p3-keccak = { git = "https://github.com/Plonky3/Plonky3" }
p3-ldt = { git = "https://github.com/Plonky3/Plonky3" }
p3-mds = { git = "https://github.com/Plonky3/Plonky3" }
p3-merkle-tree = { git = "https://github.com/Plonky3/Plonky3" }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3" }
p3-uni-stark = { git = "https://github.com/Plonky3/Plonky3" }

curta-core = { path = "core" }
curta-disassembler = { path = "disassembler" }
