[workspace]
members = [
  "cli",
  "core",
  "derive",
  "eval",
  "helper",
  "primitives",
  "prover",
  "recursion/circuit",
  "recursion/compiler",
  "recursion/core",
  "recursion/gnark-ffi",
  "recursion/program",
  "sdk",
  "zkvm/*",
]
exclude = ["examples/target"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true

[workspace.dependencies]
# p3-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-field = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-commit = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-matrix = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-baby-bear = { git = "https://github.com/Plonky3/Plonky3.git", features = [
#   "nightly-features",
# ], rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-util = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-challenger = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-dft = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-fri = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-keccak = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-keccak-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-blake3 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-merkle-tree = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-symmetric = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-uni-stark = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-maybe-rayon = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }
# p3-bn254-fr = { git = "https://github.com/Plonky3/Plonky3.git", rev = "3b5265f9d5af36534a46caebf0617595cfb42c5a" }

# For local development. 

p3-air = { path = "../my_p3_fork/Plonky3/air" }
p3-field = { path = "../my_p3_fork/Plonky3/field" }
p3-commit = { path = "../my_p3_fork/Plonky3/commit" }
p3-matrix = { path = "../my_p3_fork/Plonky3/matrix" }
p3-baby-bear = { path = "../my_p3_fork/Plonky3/baby-bear" }
p3-util = { path = "../my_p3_fork/Plonky3/util" }
p3-challenger = { path = "../my_p3_fork/Plonky3/challenger" }
p3-dft = { path = "../my_p3_fork/Plonky3/dft" }
p3-fri = { path = "../my_p3_fork/Plonky3/fri" }
p3-goldilocks = { path = "../my_p3_fork/Plonky3/goldilocks" }
p3-keccak = { path = "../my_p3_fork/Plonky3/keccak" }
p3-keccak-air = { path = "../my_p3_fork/Plonky3/keccak-air" }
p3-blake3 = { path = "../my_p3_fork/Plonky3/blake3" }
p3-mds = { path = "../my_p3_fork/Plonky3/mds" }
p3-merkle-tree = { path = "../my_p3_fork/Plonky3/merkle-tree" }
p3-poseidon2 = { path = "../my_p3_fork/Plonky3/poseidon2" }
p3-symmetric = { path = "../my_p3_fork/Plonky3/symmetric" }
p3-uni-stark = { path = "../my_p3_fork/Plonky3/uni-stark" }
p3-maybe-rayon = { path = "../my_p3_fork/Plonky3/maybe-rayon" }
p3-bn254-fr = { path = "../my_p3_fork/Plonky3/bn254-fr" }
