[workspace]
members = [
    "core",
    "cli",
    "derive",
    "zkvm/*",
    "helper",
    "eval",
    "recursion/core",
    "recursion/compiler",
]
exclude = ["examples/target"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true

[workspace.dependencies]
p3-air = { path = "../plonky3/air" }
p3-field = { path = "../plonky3/field" }
p3-commit = { path = "../plonky3/commit" }
p3-matrix = { path = "../plonky3/matrix" }
p3-baby-bear = { path = "../plonky3/baby-bear" }
p3-util = { path = "../plonky3/util" }
p3-challenger = { path = "../plonky3/challenger" }
p3-dft = { path = "../plonky3/dft" }
p3-fri = { path = "../plonky3/fri" }
p3-goldilocks = { path = "../plonky3/goldilocks" }
p3-keccak = { path = "../plonky3/keccak" }
p3-keccak-air = { path = "../plonky3/keccak-air" }
p3-blake3 = { path = "../plonky3/blake3" }
p3-mds = { path = "../plonky3/mds" }
p3-merkle-tree = { path = "../plonky3/merkle-tree" }
p3-poseidon2 = { path = "../plonky3/poseidon2" }
p3-symmetric = { path = "../plonky3/symmetric" }
p3-uni-stark = { path = "../plonky3/uni-stark" }
p3-maybe-rayon = { path = "../plonky3/maybe-rayon" }
