[workspace]
members = ["core", "cli", "derive", "examples/*", "precompiles", "zkvm"]
exclude = ["examples/target"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true

[workspace.dependencies]
p3-air = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-field = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-commit = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-matrix = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-baby-bear = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-util = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
valida-derive = { git = "https://github.com/valida-xyz/valida.git" }
p3-challenger = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-dft = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-fri = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-goldilocks = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-keccak = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-keccak-air = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-blake3 = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-mds = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-merkle-tree = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-poseidon2 = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-symmetric = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-uni-stark = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
p3-maybe-rayon = { git = "ssh://git@github.com/succinctlabs/plonky3.git", branch = "tamir/air-api-change" }
