[workspace]
members = [
    "core",
    "cli",
    "derive",
    "zkvm/*",
    "eval",
    "helper",
    "recursion/primitives",
    "recursion/constgen",
]
exclude = ["examples/target", "recursion/target"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true

[workspace.dependencies]
#p3-air = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-field = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-commit = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-matrix = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-baby-bear = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-util = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-challenger = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-dft = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-fri = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-goldilocks = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-keccak = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-keccak-air = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-blake3 = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-mds = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-merkle-tree = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-poseidon2 = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-symmetric = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-uni-stark = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }
#p3-maybe-rayon = { git = "https://github.com/succinctlabs/plonky3.git", branch = "kevjue/restore_plonky3_two_adic_fri_pcs" }

p3-air = { path = "../../plonky3/air" }
p3-field = { path = "../../plonky3/field" }
p3-commit = { path = "../../plonky3/commit" }
p3-matrix = { path = "../../plonky3/matrix" }
p3-baby-bear = { path = "../../plonky3/baby-bear" }
p3-util = { path = "../../plonky3/util" }
p3-challenger = { path = "../../plonky3/challenger" }
p3-dft = { path = "../../plonky3/dft" }
p3-fri = { path = "../../plonky3/fri" }
p3-goldilocks = { path = "../../plonky3/goldilocks" }
p3-keccak = { path = "../../plonky3/keccak" }
p3-keccak-air = { path = "../../plonky3/keccak-air" }
p3-blake3 = { path = "../../plonky3/blake3" }
p3-mds = { path = "../../plonky3/mds" }
p3-merkle-tree = { path = "../../plonky3/merkle-tree" }
p3-poseidon2 = { path = "../../plonky3/poseidon2" }
p3-symmetric = { path = "../../plonky3/symmetric" }
p3-uni-stark = { path = "../../plonky3/uni-stark" }
p3-maybe-rayon = { path = "../../plonky3/maybe-rayon" }
