[workspace]
[package]
version = "0.1.0"
name = "ed-add-zkvm"
edition = "2021"
build = "build.rs"

[dependencies]
succinct-zkvm = { path = "../../zkvm" }
hex-literal = "0.4.1"
num = { version = "0.4.1", default-features = false }

[build-dependencies]
succinct-build = { path = "../../build" }