[workspace]
[package]
version = "0.1.0"
name = "fibonacci-io-script"
edition = "2021"

[dependencies]
sp1-sdk = { path = "../../../sdk" }

[build-dependencies]
sp1-helper = { path = "../../../helper" }
