[workspace]
[package]
version = "0.1.0"
name = "cycle-tracker-zkvm"
edition = "2021"
build = "build.rs"

[dependencies]
succinct-zkvm = { path = "../../zkvm" }
succinct-derive = { path = "../../derive" }

[build-dependencies]
succinct-build = { path = "../../build" }