[package]
name = "sp1-eval"
version = "0.0.2-test"
edition = "2021"
publish = false


[dependencies]
sp1-core = { path = "../core", version = "0.0.2-test" }
sp1-prover = { path = "../prover", version = "0.0.2-test" }

clap = { version = "4.5.8", features = ["derive"] }
csv = "1.3.0"
serde = "1.0.204"
