[package]
name = "ed25519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
succinct-zkvm = { path = "../../zkvm" }
ed25519-consensus = { git = "https://github.com/penumbra-zone/ed25519-consensus.git" }
hex-literal = "0.4.1"
