[package]
name = "tendermint-script"
version = "0.0.1-test"
edition = "2021"
publish = false

[dependencies]
sp1-core = { path = "../../../core", features = [
  "neon",
], version = "0.0.1-test" }
sp1-sdk = { path = "../../../sdk", version = "0.0.1-test" }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tendermint = { version = "0.35.0", default-features = false }
tendermint-light-client-verifier = { version = "0.35.0", default-features = false, features = [
  "rust-crypto",
] }
bincode = "1.3.3"
itertools = "0.12.1"
serde_cbor = "0.11.2"
sha2 = "0.10.8"

[build-dependencies]
sp1-helper = { path = "../../../helper", version = "0.0.1-test" }
