[package]
name = "curta-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
p3-field = { workspace = true }
p3-air = { workspace = true }
p3-matrix = { workspace = true }
p3-util = { workspace = true }

[dev-dependencies]
valida-isa = { workspace = true }
