[package]
name = "sp1-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
p3-field = { workspace = true }
p3-air = { workspace = true }
p3-matrix = { workspace = true }
p3-baby-bear = { workspace = true }
elf = "0.7.4"
sp1-derive = { path = "../derive" }
p3-commit = { workspace = true }
p3-challenger = { workspace = true }
p3-dft = { workspace = true }
p3-fri = { workspace = true }
p3-goldilocks = { workspace = true }
p3-keccak = { workspace = true }
p3-keccak-air = { workspace = true }
p3-mds = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-blake3 = { workspace = true }
p3-symmetric = { workspace = true }
p3-uni-stark = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-util = { workspace = true }
itertools = "0.12.0"
rrs-lib = { git = "https://github.com/GregAC/rrs.git" }
log = "0.4.20"
num = { version = "0.4.1" }
nohash-hasher = "0.2.0"
lazy_static = "1.4"

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
tracing-log = "0.2.0"
clap = { version = "4.4.0", features = ["derive"] }
curve25519-dalek = { version = "=4.0.0" }
hex = "0.4.3"
tempfile = "3.9.0"
flate2 = "1.0.28"
size = "0.4.1"
serde_json = { version = "1.0.113", default-features = false, features = [
    "alloc",
] }
k256 = { version = "0.13.3", features = ["expose-field"] }
elliptic-curve = "0.13.8"
anyhow = "1.0.79"
serial_test = "3.0.0"

[dev-dependencies]
criterion = "0.5.1"
num = { version = "0.4.1", features = ["rand"] }
rand = "0.8.5"


[features]
perf = ["parallel"]
parallel = ["p3-maybe-rayon/parallel", "p3-blake3/parallel"]
default = ["perf"]
debug = ["parallel"]
debug-proof = ["parallel", "perf"]
serial = []
neon = ["p3-blake3/neon"]

[[bench]]
name = "main"
harness = false

[lib]
bench = false
