# RSP uses a different version of rust than the rest of SP1,
# so we need to use a different toolchain, which we achieve by
# declaring an empty workspace.
[workspace]

[package]
version = "0.1.0"
name = "rsp-script"
edition = "2021"

[dependencies]

tokio = { version = "1.21", default-features = false, features = [
    "rt",
    "rt-multi-thread",
] }
eyre = "0.6"
url = "2.3"
serde_json = "1.0.94"
serde = { version = "1.0", default-features = false, features = ["derive"] }

tracing-subscriber = "0.3.18"
dotenv = "0.15.0"
clap = { version = "4.5.7", features = ["derive", "env"] }
bincode = "1.3.3"
csv = "1.1"

# rsp
rsp-host-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "792efd0" }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "792efd0" }

alloy-provider = { version = "0.2", default-features = false, features = [
    "reqwest",
    "reqwest-rustls-tls",
] }

reth-primitives = { git = "https://github.com/sp1-patches/reth", tag = "rsp-20240827", default-features = false, features = [
    "alloy-compat",
    "optimism",
    "std",
] }

# sp1
sp1-sdk = { path = "../../../crates/sdk" }

[build-dependencies]
sp1-build = { path = "../../../crates/build" }

[features]
default = []
cuda = ["sp1-sdk/cuda"]
