[package]
version = "0.1.0"
name = "rsp-script"
edition = "2021"

[dependencies]
# tokio.workspace = true
# eyre.workspace = true
# url.workspace = true
# serde_json.workspace = true
# serde.workspace = true

tokio = { version = "1.21", default-features = false, features = [
    "rt",
    "rt-multi-thread",
] }
eyre = "0.6"
url = "2.3"
serde_json = "1.0.94"
serde = { version = "1.0", default-features = false, features = ["derive"] }

tracing-subscriber = "0.3.18"
dotenv = "0.15.0"
clap = { version = "4.5.7", features = ["derive", "env"] }
bincode = "1.3.3"
csv = "1.1"

rsp-host-executor = { git = "https://github.com/succinctlabs/rsp/" }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/"}

# # alloy
# alloy-provider.workspace = true

# # reth 
# reth-primitives.workspace = true

alloy-provider = { version = "0.2", default-features = false, features = [
    "reqwest",
    "reqwest-rustls-tls",
] }

reth-primitives = { git = "https://github.com/sp1-patches/reth", tag = "rsp-20240827", default-features = false, features = [
    "alloy-compat",
    "optimism",
    "std",
] }

# sp1
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }

[features]
default = []
cuda = ["sp1-sdk/cuda"]
