[package]
name = "rsa-script"
version = "0.0.1-test"
edition = "2021"
publish = false

[dependencies]
rsa = "0.6"
sp1-sdk = { path = "../../../sdk" }

[build-dependencies]
sp1-helper = { path = "../../../helper" }
