[package]
name = "rsa-script"
version = "1.0.0-rc.1"
edition = "2021"
publish = false

[dependencies]
rsa = "0.6"
sp1-sdk = { path = "../../../sdk", version = "1.0.0-rc.1" }

[build-dependencies]
sp1-helper = { path = "../../../helper", version = "1.0.0-rc.1" }
