[workspace]
[package]
version = "0.1.0"
name = "verifier-script"
edition = "2021"

[dependencies]
bincode = "1.3.3"
sp1-core = { path = "../../../core" }
sp1-recursion-pcs = { path = "../../pcs" }
tracing = "0.1.40"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[build-dependencies]
sp1-helper = { path = "../../../helper" }

[dev-dependencies]
sp1-recursion = { path = "../../primitives" }
