[workspace]
members = ["*"]
exclude = ["target"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true

[workspace.dependencies]
succinct-zkvm = { path = "../../zkvm" }

[patch.crates-io]
# Patch sha2 so we can use sha precompiles
sha2-v0-9-8 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git", package = "sha2", branch = "v0.9.8" }
sha2-v0-10-6 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git", package = "sha2", branch = "main" }
# Patch time because newer version breaks with older toolchains
time = { git = "https://github.com/time-rs/time.git", rev = "v0.3.28" }
ed25519-consensus = { git = "https://github.com/succinctlabs/ed25519-consensus-private.git" }