[workspace]
[package]
version = "0.1.0"
name = "num-compare-script"
edition = "2021"

[dependencies]
serde = "1.0.197"
serde_json = "1.0.114"
sp1-core = { path = "../../../core" }

[build-dependencies]
sp1-helper = { path = "../../../helper" }
