[workspace]
[package]
version = "0.1.0"
name = "unnamed-zkvm"
edition = "2021"
build = "build.rs"

[dependencies]
succinct-zkvm = { path = "../../zkvm" }

[build-dependencies]
succinct-build = { path = "../../build" }