[package]
name = "io-script"
version = "0.0.1-test"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
sp1-sdk = { path = "../../../sdk", version = "0.0.1-test" }

[build-dependencies]
sp1-helper = { path = "../../../helper", version = "0.0.1-test" }
