[workspace]
[package]
name = "io-program"
version = "0.0.1-test"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint", version = "0.0.1-test" }
serde = { version = "1.0.195", features = ["derive"] }
