[workspace]
[package]
name = "sp1-recursion-gnark-cli"
version = "0.0.1-test"
edition = "2021"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
sp1-recursion-gnark-ffi = { path = "../gnark-ffi", features = ["native"] }
clap = { version = "4.3.8", features = ["derive"] }
bincode = "1.3.3"
