[workspace]
[package]
version = "0.1.0"
name = "io-zkvm"
edition = "2021"

[dependencies]
curta-zkvm = { path = "../../../zkvm" }
serde = { version = "1.0.195", features = ["derive"] }
bincode = "1.3.3"