[package]
name = "sp1-recursion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp1-core = { path = "../../core" }
sp1-recursion-macros = { path = "../constgen" }
p3-baby-bear = { workspace = true }
p3-air = { workspace = true }
p3-challenger = { workspace = true }
p3-commit = {workspace = true}
p3-field = { workspace = true }
p3-fri = { workspace = true }
p3-matrix = { workspace = true }
p3-util = { workspace = true }

cfg-if = "1.0"
itertools = "0.12.1"