[package]
name = "aggregation-script"
version = "0.0.0-test"
edition = "2021"
publish = false

[dependencies]
hex = "0.4.3"
sp1-sdk = { path = "../../../sdk" }
tracing = "0.1.40"

[build-dependencies]
sp1-helper = { path = "../../../helper" }
