[package]
name = "aggregation-script"
version = "1.0.0-rc.1"
edition = "2021"
publish = false

[dependencies]
hex = "0.4.3"
sp1-sdk = { path = "../../../sdk", version = "1.0.0-rc.1" }
tracing = "0.1.40"

[build-dependencies]
sp1-helper = { path = "../../../helper", version = "1.0.0-rc.1" }
