[workspace]
[package]
name = "chess-program"
version = "0.0.2-test"
edition = "2021"
publish = false

[dependencies]
chess = "3.2.0"
sp1-zkvm = { path = "../../../zkvm/entrypoint", version = "0.0.2-test" }
