[workspace]
[package]
name = "chess-program"
version = "1.0.0-rc.1"
edition = "2021"
publish = false

[dependencies]
chess = "3.2.0"
sp1-zkvm = { path = "../../../zkvm/entrypoint", version = "1.0.0-rc.1" }
