[package]
name = "sp1-recursion-compiler"
version = "0.0.2-test"
edition = "2021"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air = { workspace = true }
p3-bn254-fr = { workspace = true }
p3-baby-bear = { workspace = true }
p3-commit = { workspace = true }
p3-field = { workspace = true }
p3-fri = { workspace = true }
p3-matrix = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-symmetric = { workspace = true }
p3-util = { workspace = true }

sp1-core = { path = "../../core", version = "0.0.2-test" }
sp1-primitives = { path = "../../primitives", version = "0.0.2-test" }
sp1-recursion-core = { path = "../core", version = "0.0.2-test" }
sp1-recursion-core-v2 = { path = "../core-v2", version = "0.0.2-test" }
sp1-recursion-derive = { path = "../derive", version = "0.0.2-test" }

itertools = "0.13.0"
serde = { version = "1.0.204", features = ["derive"] }
backtrace = "0.3.71"
tracing = "0.1.40"

[dev-dependencies]
p3-challenger = { workspace = true }
p3-dft = { workspace = true }
p3-merkle-tree = { workspace = true }
rand = "0.8.5"
