[package]
name = "json-script"
version = "1.0.0-rc.1"
edition = "2021"
publish = false

[dependencies]
serde = "1.0.197"
serde_json = "1.0.114"
sp1-sdk = { path = "../../../sdk", version = "1.0.0-rc.1" }
lib = { path = "../lib", version = "1.0.0-rc.1" }

[build-dependencies]
sp1-helper = { path = "../../../helper", version = "1.0.0-rc.1" }
