[workspace]
[package]
name = "zeth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
succinct-zkvm = { path = "../../../zkvm" }
succinct-precompiles = { path = "../../../precompiles" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
zeth-lib = { git = "ssh://git@github.com/succinctlabs/zeth-private.git", branch = "chris/zeth-lib", default-features = false }
ahash = "=0.8.6"

[patch.crates-io]
# Patch sha2 so we can use sha precompiles
sha2-v0-10-6 = { git = "https://github.com/succinctbot/RustCrypto-hashes.git", package = "sha2", branch = "main" }
# Patch time because newer version breaks with older toolchains
time = { git = "https://github.com/time-rs/time.git", rev = "v0.3.28" }
alloy-primitives-v0-6-2 = { git = "ssh://git@github.com/succinctlabs/alloy-core-private", package = "alloy-primitives", branch = "patch-v0.6.2" }
