[workspace]
[package]
name = "cycle-tracking-program"
version = "1.0.0-rc.1"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint", version = "1.0.0-rc.1" }
sp1-derive = { path = "../../../derive", version = "1.0.0-rc.1" }
