[workspace]
[package]
name = "cycle-tracking-program"
version = "0.0.0-test"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../zkvm/entrypoint" }
sp1-derive = { path = "../../../derive" }
