name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

permissions: 
  contents: write
  pull-requests: write 

jobs:
  benchmark:
    runs-on: macos-latest-large
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.PRIVATE_PULL_TOKEN }}@github.com".insteadOf ssh://git@github.com

      - name: rust-cache
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.rustup/
          key: test-rust-nightly-2023-12-19-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: rust-nightly-2023-12-19-
          
      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-12-19
          override: true

      - name: Install cargo criterion
        run: cargo install cargo-criterion
      
      - name: Install criterion table
        run: cargo install criterion-table

      - name: Run benchmark
        run: cd core && cargo criterion --message-format=json --features perf | criterion-table > BENCHMARKS.md

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: core/BENCHMARKS.md
          comment_tag: execution
