name: Performance Main

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: vm

      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.PRIVATE_PULL_TOKEN }}@github.com".insteadOf ssh://git@github.com

      - name: rust-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.rustup/
          key: test-rust-nightly-2023-12-19-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: rust-nightly-2023-12-19-

      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-12-19
          override: true

      - name: Install cargo criterion
        run: cd vm && cargo install cargo-criterion

      - name: Cache main.json
        uses: actions/cache@v2
        with:
          path: vm/core/main.json
          key: perf-main-${{ github.sha }}

      - name: Run pr benchmark
        run: cd vm/core && cargo criterion --message-format=json --features perf > main.json && cat main.json