name: Testing Suite

on:
  workflow_dispatch:
    inputs:
      workloads:
        description: "list of workloads to run"
        required: true
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-cpu:
    name: ${{ matrix.workload.s3_folder }} (cpu)
    runs-on: ["runs-on", "runner=64cpu-linux-x64", "spot=false", "run-id=${{ github.run_id }}"]
    strategy:
      matrix:
        workload: ${{ fromJSON(github.event.inputs.workloads) }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
          aws-region: us-west-2

      - name: Copy files from S3
        run: |
          mkdir -p workdir
          aws s3 cp s3://sp1-testing-suite/${{ matrix.workload }}/program.bin workdir/program.bin
          aws s3 cp s3://sp1-testing-suite/${{ matrix.workload }}/stdin.bin workdir/stdin.bin

      - name: Run sp1-perf
        uses: actions-rs/cargo@v1
        with:
          command: run
          toolchain: 1.81.0
          args: --release -p sp1-perf -- --program workdir/program.bin --stdin workdir/stdin.bin --mode cpu
        env:
          RUST_LOG: info
          RUSTFLAGS: -Copt-level=3 -Ctarget-cpu=native
          RUST_BACKTRACE: 1