name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "core/**"
      - "recursion/**"
      - "sdk/**"
      - "examples/fibonacci/**"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: SP1 Prover E2E
    runs-on: warp-ubuntu-latest-arm64-32x
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p sp1-prover --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1
          FRI_QUERIES: 1
          SP1_DEV_WRAPPER: false

  test-main:
    name: SP1 Tests
    runs-on: warp-ubuntu-latest-arm64-32x
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_LOG: 1
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 1
          FRI_QUERIES: 1
          SP1_DEV_WRAPPER: false

  lints:
    name: Formatting & Clippy
    runs-on: warp-ubuntu-latest-arm64-8x
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.PULL_TOKEN }}

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          CARGO_INCREMENTAL: 1
